#!/bin/bash
apt-get update
apt-get install --no-install-recommends -y \
    curl xz-utils make libffi-dev libssl-dev zlib1g-dev libreadline-dev liblzma-dev libncurses-dev libbz2-dev libsqlite3-dev

mkdir "$PYTHON_DIR"
echo "Downloading $PYTHON_URL to $PYTHON_DIR..."
curl -L "$PYTHON_URL" | tar -xJ -C "$PYTHON_DIR" --strip-components=1
cd "$PYTHON_DIR"
./configure --prefix=/code/"$PYTHON_DIR" $(if [ "$ARCH" = amd64 -a "$(echo "$PYTHON_DIR" | cut -d. -f2)" -ge 8 ]; then echo --enable-optimizations; fi)
make -j"$(nproc)"
make install
cd /code && tar czvf "$PYTHON_DIR-$ARCH.tar.gz" "$PYTHON_DIR"
