#!/bin/bash
apt-get update
apt-get install --no-install-recommends -y \
    curl xz-utils make libssl-dev zlib1g-dev libreadline-dev liblzma-dev libncurses-dev libbz2-dev

mkdir "$PYTHON_DIR"
echo "Downloading $PYTHON_URL to $PYTHON_DIR..."
curl -L "$PYTHON_URL" | tar -xJ -C "$PYTHON_DIR" --strip-components=1
cd "$PYTHON_DIR"
./configure --prefix=/code/"$PYTHON_DIR" --enable-optimizations
make -j"$(nproc)"
make install
cd /code && tar czvf "$PYTHON_DIR.tar.gz" "$PYTHON_DIR"
